import React, { useEffect, useState } from "react";
import { apiFetch } from "../lib/api";

export default function OwnerOperationsPage({ locale="ar" }) {
  const isAr=locale==="ar"; const [data,setData]=useState(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(null);
  const load=()=>apiFetch("/api/owner/commissions").then(setData).catch(e=>setError(e.status===403?(isAr?"هذه الصفحة متاحة للـ Owner وAdmin.":"Owner/Admin accounts only."):e.message));
  useEffect(()=>{load();},[]);
  async function transfer(c){ const pin=window.prompt(isAr?"إذا كان شام كاش يطلب PIN لهذه العملية أدخله الآن. اتركه فارغاً للمحاولة دون PIN.":"Enter the Sham Cash PIN if required, or leave blank.",""); if(pin===null)return; setBusy(c.id); try{await apiFetch(`/api/owner/commissions/${c.id}/transfer`,{method:"POST",body:JSON.stringify({pin:pin||null})});await load();}catch(e){setError(e.message);}finally{setBusy(null);} }
  return <main className="min-h-[75vh] bg-milk px-5 py-12" dir={isAr?"rtl":"ltr"}><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="omb-eyebrow-label text-aubergine/65">FINANCE & SHAM CASH</p><h1 className="mt-2 text-4xl font-black">{isAr?"التحصيل والعمولات":"Payments & commissions"}</h1></div><a href="/admin/orders" className="omb-btn omb-btn-secondary">{isAr?"الطلبات":"Orders"}</a></div>
  {error&&<p className="mt-6 border border-red-300 bg-red-50 p-3 text-red-700">{error}</p>}{data&&<><div className="mt-8 grid gap-4 sm:grid-cols-3">{[[isAr?"مدفوع":"Paid",data.summary.paid_usd],[isAr?"معلّق":"Pending",data.summary.pending_usd],[isAr?"عدد العمليات":"Operations",(data.summary.paid_count||0)+(data.summary.pending_count||0)]].map(([l,v],i)=><div className="border border-espresso/10 bg-oat/20 p-5" key={l}><p className="text-xs font-black text-aubergine/60">{l}</p><strong className="mt-2 block text-3xl">{i<2?`$${Number(v).toFixed(2)}`:v}</strong></div>)}</div><p className="mt-5 text-sm text-espresso/60">{isAr?`Sham Cash: ${data.sham_cash.enabled?"مفعّل":"غير مفعّل"} · التحويل التلقائي: ${data.sham_cash.auto_transfer?"نعم":"لا"}`:`Sham Cash: ${data.sham_cash.enabled?"enabled":"disabled"} · Auto: ${data.sham_cash.auto_transfer?"yes":"no"}`}</p><div className="mt-6 overflow-x-auto border border-espresso/10"><table className="w-full min-w-[900px] text-sm"><thead className="bg-oat/30"><tr><th className="p-3 text-start">Order</th><th>Type</th><th>Amount</th><th>Status</th><th>Transaction</th><th>Action</th></tr></thead><tbody>{data.commissions.map(c=><tr key={c.id} className="border-t border-espresso/10"><td className="p-3 font-black">{c.order?.reference}</td><td className="text-center">{c.type}</td><td className="text-center">${Number(c.amount_usd).toFixed(2)}</td><td className="text-center">{c.status}</td><td className="text-center text-xs">{c.provider_transaction_id||c.failure_reason||"—"}</td><td className="p-3 text-center">{data.can_transfer&&c.status==="pending"&&Number(c.amount_usd)>0?<button disabled={busy===c.id} onClick={()=>transfer(c)} className="omb-btn omb-btn-primary min-h-9 px-4 text-xs">{isAr?"تحويل عبر شام كاش":"Transfer"}</button>:"—"}</td></tr>)}</tbody></table></div></>}</div></main>;
}
